
# Azure配置
CLIENT_ID: "736efa73-315a-4b77-a273-0447f5e2a27d"
CLIENT_SECRET: "SmK8Q~kGj~gKhSU0ZFE.Z0VC~6NMMvQ8qdBm4atq"
AUTHORITY: "https://login.microsoftonline.com/common"
REDIRECT_URI: "http://localhost:8000/auth_callback"

# ---------------------------- 数据库连接配置 ----------------------------
db_config:
  host: "localhost"
  user: "root"
  password: "root"  # 注意：删除操作中使用的是1234，请保持一致
  database: "booking_system_db"
