
# Azure configuration
CLIENT_ID: "736efa73-315a-4b77-a273-0447f5e2a27d"
CLIENT_SECRET: "Cj.8Q~szh8vD3fqUi7i3VgJAgAyI1r.2brZhTdrC"
AUTHORITY: "https://login.microsoftonline.com/common"
REDIRECT_URI: "https://101.200.197.132:8000/auth_callback"

# ---------------------------- Database connection configuration ----------------------------
db_config:
  host: "localhost"
  user: "root"
  password: "8e397a5310016d27"  # Note 1234 is used in the deletion operation, please keep it the same
  database: "booking_system_db"
